apiVersion: platform.kimera.dev/v1alpha1
kind: DevelopmentEnvironment
metadata:
  labels:
    app.kubernetes.io/name: kimera-operator
    app.kubernetes.io/managed-by: kustomize
  name: demo
spec:
  image: codercom/code-server:latest
  resources:
    cpuRequest: 250m
    cpuLimit: "1"
    memoryRequest: 512Mi
    memoryLimit: 1Gi
  storage:
    size: 2Gi
    retentionPolicy: Retain
  network:
    enabled: true
    host: demo.kimera.local
