apiVersion: platform.kimera.dev/v1alpha1
kind: DevelopmentEnvironment
metadata:
  labels:
    app.kubernetes.io/name: kimera-operator
    app.kubernetes.io/managed-by: kustomize
  name: demo
spec:
  suspended: false
  image: ghcr.io/coder/code-server:4.104.2
  resources:
    cpuRequest: 250m
    cpuLimit: "1"
    memoryRequest: 512Mi
    memoryLimit: 1Gi
  storage:
    size: 2Gi
    retentionPolicy: Retain
#  source:
#    git:
#      url: https://github.com/octocat/Hello-World.git
#      revision: master
  network:
    enabled: true
    host: demo.kimera.local
